#---------------------------------#
#            Rock RMS             #
#---------------------------------#

# version format
version: 1.3.{build}

# increment flag
pull_requests:
  do_not_increment_build_number: true


# branches to build
branches:
  only:
    - master
    - beta
    - alpha
    - gauntlet

# Do not build on tags (GitHub only)
skip_tags: true


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2


# clone directory
clone_folder: c:\projects\Rock

# set clone depth
clone_depth: 1

# environment variables
environment:
  NODE_ENV: production
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  priv_key:
    secure: MIIEpAIBAAKCAQEAvLvf+Orblx7cByPn4XrryeiIniS8Jpqwti/M2m9IO50IxygS BALaU9mIyAgPGaj/aToKoifHji5jZwz4rBHEFYksnml+DudkKdwFy/aosbQPkUmF qYxZU+woA1alnk7OXTs7gO4LcQylpWAHvgFqFfQCyu8w9GxmEhKav8W+DHqKu1P6 MtHfH4azi53TPJXII/y6+8t84Jtjk9vOa3BddvWRPrtZ0xcXk4M2c/aGwoRZANWn 70GaxdGc3RvuTJHwUwzFXuqW3aU2DDQS8qMzHbkrRpdjCZ0jewHHKj0imiVPApQf agwE/nHselxSyKn5BllE9v3bIZyTFeCc4l89GQIDAQABAoIBACYhq0HGabFhqcDD j2DuDd+QXLHe6CjAjj1w8OmdHDH3K0PZo7ItxWC1jb4karCbhWcENAvJD7d5RdoX M9LIEB7txRcIZ1CpjYIrkvw/jJvCrnaDLT8xPQcIqpjqE7IlZ+pMQlxtO+COVpVQ DqBj9sQStdG8e96WXBUAr0VZtWkdq+crJtgm7F7m/vGek6xBy28h5bePBOw4hyYk t/d/uORqjkp5g8B1/hDz/cfgFJDV4LdXiYYGY9ljobUMEqPm5imwo8Gbcs/8WU4d xp4BAneu1Era7ONqs0Kwk9pFz5LFTXOaebyEJKojI54ccn0i9sS7xHPR+Kz9fFZT NC/tQAUCgYEA8FISbnD5jPcFnkt1lEMer6EGMFMNwMAaqEwdu/A28tYafk2o3V2K 3ZKg5zk1pCT/E4G5ximpsr1S3xnuHY7hBDK82ZOhok7VIlE+dyMqKVc0LwSj99k2 m9Xh4HS1tyFhpGHyxDremLzVFTgKc/XMtgF9BNe95lQKsvrj55/jFlsCgYEAyQwu gHXZFYzDPx2swTrmwUJXwV1/ruDsoHhydIniqGW+T5J5qq/dG/+RddeD6ry3h2bI MCjuvL+2iXhwO7w2F8pCyORCqea9fdhTdeGxSmoi7KRWOEa9Nb03v61HqN1rP5Pa HSlNYNgIuoscUsH6IQ4hWKBGp9DzPAqtn18IXJsCgYEA1zlZYmlxROqxsGt6GNbn s3itdzfaeEZTWWgZtQfT3jUbMwRP+DhfNkKsMYhN3vx3KLwkaTFE1luxzTaGxxf/ s2fRM7aAqkCZpotGOyJWDwIXLQil5EE3I+cvzHoZh7GwpaxG47CpS/bJiqBO1D1N Ia9BjMW+P3oCvvnsg7LwiEMCgYEAg+6xiW1Mkv63lfCkUH2VtlcR/Xuc8ab6wWep PF7L1dRGqjMmEmOsBtaUny9Ziy5ihcFmN2x1Fnn8kIPvqtOc78m0P97C/HnF+hJ+ 2onL7VhvKLnDNtT9D4nnTqqoruD2o1ckOCTFeXrrZ3colAplWVHLgjxTgYb2R31+ aGpVs2cCgYBWfBbmwWe7N7U4ZZbHuk3qWm6qK5x5G+AoH5YDTj4tg6D69CwDadUU AgG7iFut5xa0uIbhcYFO1tX15jQ1Q4hX6ZQ8ENcGmZCEd2fyA3FhvDJv0MkgTh+F MK+Ewfs7rfcHRq8bO3lsRd8Ydv7aURFWy5uMC9+idD9ekx3qnfAeFg==

cache:
  - packages                        # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules                    # local npm modules

# scripts that run after cloning repository
install:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
  - cmd: git clone -q --depth=1 git@github.com:NewSpring/rock-bookshelf.git c:\projects\Rock\.remote\rock-bookshelf
  - cmd: git clone -q --depth=1 git@github.com:NewSpring/rock-power-bi.git c:\projects\Rock\.remote\rock-power-bi




#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release


# scripts to run before build
before_build:
  - cmd: nuget restore -verbosity detailed
  - cmd: npm install --production
  - cmd: node ./node_modules/normajs/bin/norma.js build  # use cached version of norma
  - cmd: git clone -q --depth=1 https://github.com/NewSpring/rock-spiritual-gifts.git ../rock-spiritual-gifts


build:
  project: Rock.sln
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
  parallel: true
  verbosity: minimal

matrix:
  fast_finish: true    # set this flag to immediately finish build once one of the jobs fails



#---------------------------------#
#       tests configuration       #
#---------------------------------#
# to disable automatic tests
test: off




#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: RockWeb
    name: NewSpringRockKit
    type: Web Deploy Package


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

  - provider: Environment
    name: Alpha (alpha-rock.newspring.cc)
    on:
      branch: alpha

  - provider: Environment
    name: Gauntlet (gauntlet.newspring.cc)
    on:
      branch: gauntlet


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Slack
    auth_token:
      secure: 1OsoJ8x/9EYQWTaJQVCj53YgZJRiz/GSLl5VhE7ZA0wb/J5wISUoxzxhIUMSttheY0G/iQCBt1Tb/9lLaIulWw==
    channel: deployments
